apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-2-mins-deadline
spec:
  schedule: "36,38,40,42,44,46,48 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec: 
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: luksa/batch-job