apiVersion: v1 
kind: Pod
metadata:
  name: kubia-multiport-pod
  labels:
    app: kubia-multiport
spec:
  containers:
  - name: kubia-miltiport-pod
    image: luksa/kubia
    ports: 
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
---
apiVersion: v1 
kind: Service
metadata:
  name: kubia-miltiport-service
  labels:
    app: kubia-multiport
spec:
  ports:
  - name: http
    port: 80
    targetPort: http 
  - name: https 
    port: 443
    targetPort: https